---
- name: CONTOSO.com member server configuration
  hosts: member_servers

  roles:
    - { role: common }

  tasks:
  - name: Configure DNS Server
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses:
      - 192.168.100.10

  - name: Verify server is a member of CONTOSO.com
    win_domain_membership:
      hostname: "{{ inventory_hostname }}"
      dns_domain_name: CONTOSO.com
      domain_admin_user: test_admin@CONTOSO.com
      domain_admin_password: "AutomationDoesW0rk!"
      state: domain
    register: domain_state

  - name: Reboot to complete joining domain
    when: domain_state.changed
    win_reboot:
      shutdown_timeout: 600
      reboot_timeout: 600
      post_boot_delay: 120

  - name: Verify File Server Role is installed.
    win_feature:
      name: File-Services, FS-FileServer
      state: present
      include_management_tools: True

  - name: Ensure directory structure for public share exists
    win_file:
      path: C:\shares\public
      state: directory

  - name: Ensure public share exists
    win_share:
      name: public
      description: Basic RW share for all domain users
      path: C:\shares\public
      list: yes
      full: Administrators
      change: Users